-- Facebook Organic Post Performance — synced from the Facebook Graph API by
-- .github/workflows/facebook-sync.yml (scripts/sync-facebook-performance.js)
-- on a schedule. The admin dashboard only ever reads this table; nothing in
-- the browser talks to Facebook directly. Run once in Supabase → SQL Editor.
-- Idempotent.

create table if not exists facebook_post_performance (
  id               bigint generated by default as identity primary key,
  page_name        text        not null,          -- e.g. 'Kapruka FB'
  page_id          text        not null,           -- Facebook Page ID
  post_id          text        not null,           -- Facebook Post ID
  message          text,                            -- post caption (truncated)
  permalink_url    text,
  post_type        text,                            -- photo | video | link | status | reel
  created_time     timestamptz,                     -- when the post was published
  impressions      integer,
  reach             integer,                        -- post_impressions_unique
  engaged_users    integer,
  clicks            integer,
  reactions_total  integer,
  comments_count   integer,
  shares_count     integer,
  synced_at        timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (page_id, post_id)
);

create index if not exists idx_fb_post_performance_created
  on facebook_post_performance (created_time desc);

-- The sync job and the admin dashboard both talk to Supabase with the anon
-- key (same model as every other table in this app), so allow anon/
-- authenticated to read, insert, and update (update is required for the
-- upsert-on-conflict the sync job performs to refresh metrics on existing
-- posts).
alter table facebook_post_performance enable row level security;

drop policy if exists facebook_post_performance_read on facebook_post_performance;
create policy facebook_post_performance_read
  on facebook_post_performance for select using (true);

drop policy if exists facebook_post_performance_insert on facebook_post_performance;
create policy facebook_post_performance_insert
  on facebook_post_performance for insert with check (true);

drop policy if exists facebook_post_performance_update on facebook_post_performance;
create policy facebook_post_performance_update
  on facebook_post_performance for update using (true) with check (true);

grant select, insert, update on facebook_post_performance to anon, authenticated;
grant usage, select on sequence facebook_post_performance_id_seq to anon, authenticated;
