-- Tracks which organic "winner" posts have already been pushed into paid ads
-- by scripts/weekly-organic-winners-to-ads.js. Prevents the weekly job from
-- creating a duplicate ad for the same post if it's still a top performer
-- (or still inside the 7-day window) on a later run. Idempotent.

create table if not exists organic_winner_ad_pushes (
  id                 bigint generated by default as identity primary key,
  group_key          text        not null,           -- caption+date grouping key (see script)
  platforms          text        not null,            -- e.g. 'facebook,instagram'
  message_excerpt    text,
  creative_source    text        not null,            -- 'sheet_match' | 'reused_post'
  matched_content_id text,                             -- Content ID from the creative sheet, if matched
  cta_link           text,
  ad_id              text,
  adset_id           text        not null,
  status             text        not null default 'created',
  pushed_at          timestamptz not null default now(),
  unique (group_key)
);

alter table organic_winner_ad_pushes enable row level security;

drop policy if exists organic_winner_ad_pushes_read on organic_winner_ad_pushes;
create policy organic_winner_ad_pushes_read
  on organic_winner_ad_pushes for select using (true);

drop policy if exists organic_winner_ad_pushes_insert on organic_winner_ad_pushes;
create policy organic_winner_ad_pushes_insert
  on organic_winner_ad_pushes for insert with check (true);

grant select, insert on organic_winner_ad_pushes to anon, authenticated;
grant usage, select on sequence organic_winner_ad_pushes_id_seq to anon, authenticated;
