-- Studio Activity Log — an append-only audit trail for every studio_calendar slot.
-- Run once in Supabase → SQL Editor. Idempotent.
--
-- Every meaningful event on a slot is recorded here: creation, status changes,
-- Head approve/reject (with reason), DM approve/reject (with reason), Hold (with
-- reason), assignment, and content-description edits. The admin studio calendar
-- reads these back and shows a per-slot history timeline in the slot popup.
--
-- `actor` is best-effort (there is no real login): 'Content Head',
-- 'Digital Marketing', 'Studio', 'Admin', or 'System'.

create table if not exists studio_activity_log (
  id          bigint generated by default as identity primary key,
  slot_id     bigint,                                   -- studio_calendar.id
  event_type  text   not null,                          -- created|status_changed|rejected|hold|assigned|content_edited
  detail      text,                                     -- human-readable description (includes reasons)
  actor       text   default 'System',
  created_at  timestamptz not null default now()
);

create index if not exists idx_studio_activity_slot
  on studio_activity_log (slot_id, created_at);

-- The app talks to Supabase with the anon key, so allow anon/authenticated to
-- read and insert (append-only — no update/delete granted).
alter table studio_activity_log enable row level security;

drop policy if exists studio_activity_log_read on studio_activity_log;
create policy studio_activity_log_read
  on studio_activity_log for select using (true);

drop policy if exists studio_activity_log_insert on studio_activity_log;
create policy studio_activity_log_insert
  on studio_activity_log for insert with check (true);

grant select, insert on studio_activity_log to anon, authenticated;
grant usage, select on sequence studio_activity_log_id_seq to anon, authenticated;
