-- User accounts + per-tool access grants for the Kapruka Digital Marketing
-- Portal. Run once in Supabase → SQL Editor. Idempotent.
--
-- SECURITY: unlike every other table in sql/, these three tables are NOT
-- opened up to the anon/authenticated roles. The portal's browser code only
-- ever holds the Supabase anon key (it's public by design — visible in page
-- source), so if these tables granted anon access, anyone could read
-- password hashes or rewrite their own tool grants from the browser console.
--
-- Instead: RLS is enabled with zero policies, and nothing is granted to
-- anon/authenticated. That means the anon key can see and change NOTHING
-- here. The only thing that can read or write these tables is the Supabase
-- *service role* key, which bypasses RLS — and that key lives only in
-- Cloudflare Pages Functions (functions/api/*), set via
-- `wrangler pages secret put SUPABASE_SERVICE_ROLE_KEY`. It must never be
-- put in js/*.js or any file served to the browser.
--
-- users.password_hash is PBKDF2-SHA256 (210,000 iterations, random 16-byte
-- salt), computed with Web Crypto in functions/api/login.js — chosen over
-- bcrypt/scrypt because Cloudflare Workers' SubtleCrypto doesn't support
-- those, and over plain SHA-256 because that's crackable at scale.
-- Format stored: "pbkdf2$<iterations>$<base64 salt>$<base64 hash>".

create table if not exists users (
  id             bigint generated by default as identity primary key,
  username       text not null unique,       -- lowercase, used to log in
  display_name   text not null,              -- e.g. "Lahiru"
  password_hash  text not null,              -- see format note above
  role           text not null default 'user', -- 'user' | 'admin' | 'superadmin'
  active         boolean not null default true,  -- deactivated users can't log in
  last_login_at  timestamptz,                -- set by functions/api/login.js on success
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists idx_users_username on users (lower(username));

-- Canonical list of grantable tools/cards. `key` is the stable id referenced
-- by index.html / admin-dashboard.html and by user_tool_access.tool_key.
create table if not exists tools (
  key          text primary key,     -- e.g. 'seo', 'pcagent', 'revenue'
  label        text not null,        -- e.g. 'SEO Boost'
  created_at   timestamptz not null default now()
);

create table if not exists user_tool_access (
  user_id     bigint not null references users(id) on delete cascade,
  tool_key    text   not null references tools(key) on delete cascade,
  granted_at  timestamptz not null default now(),
  granted_by  text,  -- username of the admin/superadmin who granted it
  primary key (user_id, tool_key)
);

-- Keep updated_at current on edits (role change, deactivate, password reset).
create or replace function set_users_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_users_updated_at on users;
create trigger trg_users_updated_at
  before update on users
  for each row execute function set_users_updated_at();

-- Seed the known tool cards. Safe to re-run; ON CONFLICT keeps existing labels
-- if you've since renamed one via the admin UI.
insert into tools (key, label) values
  ('ads',          'Ads Manager'),
  ('daraz',        'Daraz Market Agent'),
  ('avurudhu',     'Season Checklist'),
  ('seo',          'SEO Boost'),
  ('pcagent',      'PC Agent'),
  ('revenue',      'Revenue Breakdown Report')
on conflict (key) do nothing;

-- Lock everything down: RLS on, no policies, no anon/authenticated grants.
alter table users enable row level security;
alter table tools enable row level security;
alter table user_tool_access enable row level security;

revoke all on users, tools, user_tool_access from anon, authenticated;
